name: core_util
description: core util package.
publish_to: none

environment:
  sdk: 3.8.1
  flutter: 3.32.8

dependencies:
  flutter:
    sdk: flutter

  custom_refresh_indicator: 3.1.0
  firebase_core: ^3.0.0
  flutter_svg: 2.0.10+1
  intl: 0.20.2
  shimmer: 3.0.0